// biome-ignore-all lint: generated fixture
export const messyTable = `
<table><tbody><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr><td colspan="3"></td><td colspan="3"></td><td colspan="24"><font>June 30, 2024</font></td><td colspan="3"></td><td colspan="24"><font>December 31, 2023</font></td><td colspan="3"></td><td colspan="24"><font>June 30, 2023</font></td></tr><tr><td colspan="3"><div><font>ASSETS</font></div></td><td colspan="3"></td><td colspan="12"><font>Amount</font></td><td colspan="3"></td><td colspan="9"><font>%</font></td><td colspan="3"></td><td colspan="12"><font>Amount</font></td><td colspan="3"></td><td colspan="9"><font>%</font></td><td colspan="3"></td><td colspan="12"><font>Amount</font></td><td colspan="3"></td><td colspan="9"><font>%</font></td></tr><tr><td colspan="3"></td><td colspan="3"></td><td colspan="12"></td><td colspan="3"></td><td colspan="9"></td><td colspan="3"></td><td colspan="12"></td><td colspan="3"></td><td colspan="9"></td><td colspan="3"></td><td colspan="12"></td><td colspan="3"></td><td colspan="9"></td></tr><tr><td colspan="3"><div><font>CURRENT ASSETS</font></div></td><td colspan="3"></td><td colspan="12"></td><td colspan="3"></td><td colspan="9"></td><td colspan="3"></td><td colspan="12"></td><td colspan="3"></td><td colspan="9"></td><td colspan="3"></td><td colspan="12"></td><td c... (line truncated to 2000 chars)
</table>
`;

export const messyQuotes = `
<div><font>•</font><font>Provides guidance to enhance the requirements of aggregation and disaggregation: The Company shall identify the assets, liabilities, equity, income, expenses and cash flows that arise from individual transactions or other events and shall classify and aggregate them into groups based on shared characteristics, so as to result in the presentation in the primary financial statements of line items that have at least one similar characteristic. The Company shall disaggregate items with dissimilar characteristics in the primary financial statements and in the notes. The Company labels items as‘other’ only if it cannot find a more informative label.</font></div>
`;
